version: "3"

services:
  vit497_front:
    build: ./frontend
    container_name: vit497_front
    command: serve -s build -l 3000
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    # before run cmd:  docker network create v1-network
    networks:
      - v1-network

  vit497_api:
    build: ./api
    container_name: vit497_api
    command: npm run start
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      # - MONGO_URL=mongodb://vit497_api_db:27017/api
    depends_on:
      - vit497_api_db
    networks:
      - v1-network

  vit497_api_db:
    build: ./postgres
    container_name: vit497_api_db
    restart: always
    ports:
      - ${POSTGRES_BIND_IP}:${POSTGRES_PORT}:5432
    volumes:
      - pgdata_house2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata_house2:
    driver: local
    driver_opts:
      type: none
      device: /home/vit/pgdata_house2
      o: bind

networks:
  v1-network:
    external: true
