version: "3"

services:
  vit497_front:
    build:
      context: ./front
      args:
        API_URL: ${API_URL}
    container_name: vit497_front
    command: serve -s build -l 3000
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    # before run cmd:  docker network create v1-network
    networks:
      - v1-network

  vit497_api:
    build: ./back
    container_name: vit497_api
    command: npm run start
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=vit497_api_db
    depends_on:
      - vit497_api_db
    logging:
      options:
        max-size: 10m
    networks:
      - v1-network

  vit497_api_db:
    build: ./postgres
    container_name: vit497_api_db
    restart: always
    volumes:
      - pgdata_house2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
    networks:
      - v1-network

volumes:
  pgdata_house2:
    driver: local
    driver_opts:
      type: none
      device: /home/vit/work/pgdata_house2
      o: bind

networks:
  v1-network:
    external: true
