version: "3"

services:
  vit497_front:
    build: ./front
    container_name: vit497_front
    command: serve -s build -l 3000
    restart: unless-stopped
    environment:
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
      - REACT_APP_API_PORT=${REACT_APP_API_PORT}
    # before run cmd:  docker network create v1-network
    networks:
      - v1-network

  vit497_api:
    build: ./back
    container_name: vit497_api
    command: npm run start
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - vit497_api_db
    networks:
      - v1-network

  vit497_api_db:
    build: ./postgres
    container_name: vit497_api_db
    restart: always
    volumes:
      - pgdata_house2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  pgdata_house2:
    driver: local
    driver_opts:
      type: none
      device: /home/vit/pgdata_house2
      o: bind

networks:
  v1-network:
    external: true
